services:
    gateway:
        build: .
        ports:
            - 3006:3006
        depends_on:
            - rabbitmq
        restart: unless-stopped
        env_file:
            - .env

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
volumes:
    rabbitmq_data:
