services:
    gateway:
        build: .
        ports:
            - 8000:8000
        env_file:
            - .env
        depends_on:
            - mysql
        restart: unless-stopped
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
volumes:
    rabbitmq_data:
